seed: 1

num_poses: 100
rotation_noise: 0.05
translation_noise: 0.02
loop_closure_ratio: 0.2
loop_closure_outlier_ratio: 0.05


inner_optim:
  optimizer_cls: GaussNewton
  max_iters: 10
  step_size: 0.1
  backward_mode: implicit
  verbose: true
  track_err_history: true
  keep_step_size: true
  regularize: true
  ratio_known_poses: 0.1
  reg_w: 1e-4

outer_optim:
  lr: 0.1
  num_epochs: 20

hydra:
  run:
    dir: examples/outputs