seed: 1

num_poses: 2048
rotation_noise: 0.05
translation_noise: 0.02
loop_closure_ratio: 0.4
loop_closure_outlier_ratio: 0.25
dataset_size: 128 
batch_size: 1


inner_optim:
  optimizer_cls: LevenbergMarquardt
  solver: sparse
  max_iters: 10 
  step_size: 0.1
  backward_mode: implicit
  verbose: true
  track_err_history: true
  keep_step_size: true
  regularize: true
  ratio_known_poses: 0.1
  reg_w: 1e-3

outer_optim:
  lr: 0.1
  num_epochs: 20

hydra:
  run:
    dir: examples/outputs