name: Wheels
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  build-wheel-linux:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python_version: [["3.8", "cp38-cp38"], ["3.9", "cp39-cp39"], ["3.10", "cp310-cp310"]]
        cuda_support: [["", "--extra-index-url https://download.pytorch.org/whl/cpu", "\"['cpu', '11.3', '11.6']\"", "cpu"], ["+cu102", "", "\"['10.2']\"", "cuda102"]]
    container: pytorch/manylinux-${{ matrix.cuda_support[3] }}
    steps:
      - name: Checkout theseus
        uses: actions/checkout@v3
      - name: Install PyTorch 1.12 RC
        run: |
          export PATH="/opt/python/${{ matrix.python_version[1] }}/bin:$PATH"
          python3 -mpip install torch==1.12 ${{ matrix.cuda_support[1] }}
          python3 -mpip install "git+https://github.com/pytorch/functorch.git@release/0.2"
      - name: Install suitesparse
        run: |
          yum makecache
          yum -y install suitesparse
      - name: Build wheel
        run: |
          export PATH="/opt/python/${{ matrix.python_version[1] }}/bin:$PATH"
          python3 -m pip install wheel
          python3 -m pip install build
          python3 -m build
          # NB: wheels have the linux_x86_64 tag so we rename to manylinux1
          # find . -name 'dist/*whl' -exec bash -c ' mv $0 ${0/linux/manylinux1}' {} \;
      # pytorch/pytorch binaries are also manylinux_2_17 compliant but they
      # pretend that they're manylinux1 compliant so we do the same.
      - name: Show auditwheel output; confirm 2-17
        run: |
          python3 -mpip install auditwheel
          auditwheel show dist/*
      - name: Upload wheel for the test-wheel job
        uses: actions/upload-artifact@v2
        with:
          name: theseus-linux-${{ matrix.python_version[0] }}.whl
          path: dist/theseus-*.whl
      - name: Upload wheel for download
        uses: actions/upload-artifact@v2
        with:
          name: theseus-batch.whl
          path: dist/*.whl
